### ISSUE TITLE
When file is created in new directory, it does not get synced right away

### ISSUE THREAD

**Issue by therontockinfiot** [gae123/sd2#2]
It appears that when a new file is created in a new directory, sd2 notices the change and tries to use scp to copy the file to the remote server.  However since the directory is new too it doesn't yet exist on the server and the scp command fails.  It can then takes several minutes before the rsync command runs and does a full sync of the directory/files.

It would be nice if sd2 could notice when the scp command files, and do an immediate 'rsync'.  Or maybe wait a couple of seconds in case there is a flurry of file changes (e.g. what happens when you do a 'git pull').

**Comment by gae123** [comment]
I took a quick look at the source, this is something that can be taken care around line 92 of fswatch_connections.py  We should just wake up the rsync activity that corresponds to this fswatrch activity.
